# Generated by Django 4.2.6 on 2023-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAPIKey',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_key',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
