# Generated by Django 4.2.6 on 2023-11-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_chatbox_result_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='modelID_fk',
        ),
        migrations.AddField(
            model_name='session',
            name='document_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='documentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
