# Generated by Django 4.2.6 on 2023-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_remove_document_modelid_fk_session_document_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
