# Generated by Django 4.2.6 on 2023-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_document_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
