# Generated by Django 4.2.6 on 2023-11-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_document_documentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='endtime',
        ),
    ]
