# Generated by Django 4.2.6 on 2024-09-14 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_remove_chatbox_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('call_count', models.IntegerField(default=0)),
                ('last_call', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='chatbox',
            name='threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='top_k',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('resultID', models.AutoField(primary_key=True, serialize=False)),
                ('word_file', models.FileField(upload_to='word_files/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.chatbox')),
                ('documentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.document')),
                ('session_fk3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.session')),
            ],
        ),
    ]
